blank_issues_enabled: false
contact_links:
  - name: Ask a question on how to use konfetty
    about: For general-purpose questions and answers, see the Discussions section.
    url: https://github.com/nikoksr/konfetty/discussions
